### ISSUE TITLE
index transactions by hash

### ISSUE THREAD

**Issue by chaosma** [OnFinality-io/subql#187]
I saw online examples of creating record with ID equals block hash. I plan to do the similar thing, i.e. record transaction by its hash. However, the substrate events or extrinsic call "balances.Transfer" doesn't include the transaction hash. From my understanding, substrate doesn't calculate the transaction hash. In this case, what's the best way to index a transaction? By the block hash and its position in the block?

**Comment by jiqiang90** [comment]
Hi @chaosma I hope you find the solution already.

First you can apply ' balance.Transfer '  in the manifest filter, and then in the mapping function try :

`const extrinsicHash = event.extrinsic.extrinsic.hash` 

to extract the transaction hash from an extrinsic in a `SubstrateEvent` type entity (see [here)](https://github.com/OnFinality-io/subql/blob/9834c5da40186860038f17526a34e99570952bab/packages/types/src/interfaces.ts#L30)

Hope that answer your question.
