### ISSUE TITLE
connect to remote wss connection

### ISSUE THREAD

**Issue by chaosma** [OnFinality-io/subql#189]
I am able to connect to blockchain running on localhost through ws connection. But when I try to connect to a remote wss connection, e.g.  in project.yml, I specified the following endpoint with my remote server's IP address.

`endpoint: "wss://xxx.xxx.xx.xxx:9944"`

After running `docker-compose up`, It will always give me connection fail. I believe it's caused by self-signed certificate on my remote server. Is there anyway to accept the CA verification. e.g. In javascript, I can use:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

**Comment by zhex** [comment]
@chaosma, could you provide the error log here?  `process.env.NODE_TLS_REJECT_UNAUTHORIZED` allow skipping the unknown CA issue. So I think this might be the other problem.

**Comment by chaosma** [comment]
> @chaosma, could you provide the error log here? `process.env.NODE_TLS_REJECT_UNAUTHORIZED` allow skipping the unknown CA issue. So I think this might be the other problem.

The error message is just "connection failed" (same message repeatedly).  I didn't put `process.env.NODE_TLS_REJECT_UNAUTHORIZED` inside the project yet, since I don't know where to put.

**Comment by zhex** [comment]
Yes, you placed the env in the right place.
Could you check the remote server port is correct? it could be 443, not 9944. 
the easiest way is to plaste your remote server address into the custom endpoint section in https://polkadot.js.org/apps/.

**Comment by ianhe8x** [comment]
usually it is not ssl-ws from port 9944

**Comment by chaosma** [comment]
Oh, my bad! I haven't realized that I forgot to change to 443. It works now. Thanks a lot! By the way, may I ask another question about localhost endpoint here?
In MacOS, I can use endpoint="ws://host.internal.docker:9944". However, in Linux, it didn't work. I tried to use the following to get the host IP: 
```
docker network inspect <project_name_default>
```
which is 172.18.0.1 in my case. 172.17.0.1 is the "default" docker network. I tried both 172.18.0.1:9944 and 172.17.0.1:9944, they all return error "connection failed".

**Comment by ianhe8x** [comment]
If you still want to use it via docker, I think --network host can help here.  
Or you can install it from npm and use it directly.

**Comment by chaosma** [comment]
I don't get it. Could you give me the whole command here? Thanks!

**Comment by ianhe8x** [comment]
I'm not using linux, but I do find a post should help in your case. It says you can use `${DOCKER_GATEWAY_HOST:-host.docker.internal}` to refer to host's ip.

https://dev.to/natterstefan/docker-tip-how-to-get-host-s-ip-address-inside-a-docker-container-5anh

**Comment by chaosma** [comment]
Thank you! I will try it.
