### ISSUE TITLE
Is it possible to support configuration of typesbundle ?

### ISSUE THREAD

**Issue by ntduan** [OnFinality-io/subql#91]
https://github.com/OnFinality-io/subql/blob/8d1dd79c7607e84fe335f9354de3e78a56ddabac/packages/node/src/indexer/api.service.ts#L13-L19

Only configuration types are supported now. So I can't configure types based on the specVersion of the chain . It is recommended to add configuration for typesBundle typesAlias typesChain and typesSpec, just like @polkadot/api.

https://github.com/polkadot-js/api/blob/master/packages/types/src/types/registry.ts#L59-L81

**Comment by ianhe8x** [comment]
Sure it can be added.
